#!/bin/bash

# This script merely testes if the compiler does not crash while compiling the files
# It does not check the code the compiler generates

PROG_BEGIN='python3 main.py test.yal '
ERRORS=0

echo '--- CORRECT FILES START ---'
for file_name in files/correct/*.yal; do
  python3 main.py $file_name --quiet
  RET_VALUE=$?
  if [ $RET_VALUE -eq 0 ]
  then
    echo "OK '$file_name'"
  elif [ $RET_VALUE -eq 10 ]
  then
    echo "ERROR --> '$file_name'"
    ERRORS=$ERRORS+1
  else
    echo "FATAL ERROR ---> $file_name"
    exit 1
  fi
done
echo '--- CORRECT FILES END ---'

echo '--- ERROR FILES START ---'
for file_name in files/errors/*.yal; do
  python3 main.py $file_name --quiet
  RET_VALUE=$?
  if [ $RET_VALUE -eq 10 ]
  then
    echo "OK '$file_name'"
  elif [ $RET_VALUE -eq 1 ]
  then
    echo "ERROR --> $file_name"
    $ERRORS=$ERRORS+1
  else
    echo "FATAL ERROR ---> $file_name"
    exit 1
  fi
done
echo '--- ERROR FILES END ---'

if [ $ERRORS -ge 1 ]
then
  echo ""
  echo "---> $ERRORS errors on testing! <---"
else
  echo ""
  echo "---> SUCCESS <---"
fi
